name: MSVC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-msvc:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install OpenSSL
      run: |
        choco install openssl -y
        
    - name: Verify OpenSSL Installation
      run: |
        if (Test-Path "C:/Program Files/OpenSSL-Win64") {
          Write-Host "OpenSSL found at: C:/Program Files/OpenSSL-Win64"
          Get-ChildItem "C:/Program Files/OpenSSL-Win64"
        } elseif (Test-Path "C:/Program Files/OpenSSL") {
          Write-Host "OpenSSL found at: C:/Program Files/OpenSSL"
          Get-ChildItem "C:/Program Files/OpenSSL"
        } else {
          Write-Host "Searching for OpenSSL..."
          Get-ChildItem "C:/Program Files" | Where-Object {$_.Name -like "*OpenSSL*"}
        }

    - name: Install CMake 4.0+
      run: |
        choco install cmake --version=4.1.2 -y --force
        cmake --version

    - name: Configure CMake
      shell: pwsh
      run: |
        # Auto-detect OpenSSL path
        $openssl_path = if (Test-Path "C:/Program Files/OpenSSL-Win64") {
          "C:/Program Files/OpenSSL-Win64"
        } elseif (Test-Path "C:/Program Files/OpenSSL") {
          "C:/Program Files/OpenSSL"
        } else {
          $null
        }
        
        if ($null -eq $openssl_path) {
          Write-Error "OpenSSL not found!"
          exit 1
        }
        
        Write-Host "Using OpenSSL at: $openssl_path"
        
        cmake -B "${{ github.workspace }}/build" `
          -G "Visual Studio 17 2022" `
          -A x64 `
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DOPENSSL_ROOT_DIR="$openssl_path" `
          -S "${{ github.workspace }}"

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} -j 2

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: openai-asio-windows-msvc-${{ matrix.build_type }}
        path: |
          ${{ github.workspace }}/build/${{ matrix.build_type }}/*.lib
          ${{ github.workspace }}/build/${{ matrix.build_type }}/*.exe
        retention-days: 7

